name: hotel_booking_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  provider: ^5.0.0
  syncfusion_flutter_datepicker: ^19.1.69-beta
  mapbox_gl: ^0.12.0
  mapbox_search: ^2.1.0+1
  http: ^0.13.3
  photo_view: ^0.11.1
  modal_bottom_sheet: ^2.0.0
  flutter_typeahead: ^3.1.3
  flutter_svg: ^0.22.0
  flutter_map: ^0.13.1
  latlong2: ^0.8.0
  image_picker: ^0.8.1+3
  cloud_firestore: ^2.3.0
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  firebase_storage: ^9.0.0
  cached_network_image: ^3.1.0
  location: ^4.3.0
  cloud_functions: ^3.0.0
  credit_card_input_form: ^2.3.0
  stripe_payment: ^1.1.4
  url_launcher: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/home_background.png
    - assets/images/hotel_1.png
    - assets/images/hotel_2.png
    - assets/images/hotel_3.png
    - assets/images/hotel_detail_1.png
    - assets/images/hotel_detail_2.png
    - assets/images/hotel_detail_3.png
    - assets/images/hotel_detail_4.png
    - assets/images/hotel.jpg
    - assets/images/login_background.png
    - assets/images/amex.png
    - assets/images/mastercard.png
    - assets/images/visacard.png
    - assets/images/discover.png
    - assets/images/card_background.jpg
    - assets/images/stripe.png

    #icon
    - assets/images/icons/fireplace.svg
    - assets/images/icons/fire_pit.svg
    - assets/images/icons/grill.svg
    - assets/images/icons/gym_equipment.svg
    - assets/images/icons/hot_tub.svg
    - assets/images/icons/outdoor_dining_area.svg
    - assets/images/icons/patio.svg
    - assets/images/icons/pool.svg
    - assets/images/icons/pool_table.svg
    - assets/images/icons/air-conditioner.svg
    - assets/images/icons/kitchen.svg
    - assets/images/icons/wifi.svg
    - assets/images/icons/coffee.svg
    - assets/images/icons/money-back.svg
    - assets/images/icons/dryer.svg
    - assets/images/icons/heater.svg
    - assets/images/icons/beach_access.svg
    - assets/images/icons/ev_charger.svg
    - assets/images/icons/free_parking.svg
    - assets/images/icons/game_console.svg
    - assets/images/icons/first_aid_kit.svg
    - assets/images/icons/elevator.svg 
    - assets/images/icons/lake_access.svg
    - assets/images/icons/entertainment.svg
    - assets/images/icons/heating_and_coolingg.svg
    - assets/images/icons/family.svg
    - assets/images/icons/internet_and_office.svg
    - assets/images/icons/amenities.svg
    - assets/images/icons/fire-extinguisher.svg


    
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
