class IconLib {
  static Map<String, String> iconRoomLib = {
    "Refundable": "assets/images/icons/money-back.svg",
    "Breakfast included": "assets/images/icons/coffee.svg",
    "Air conditional": "assets/images/icons/air-conditioner.svg",
    "Elevator": "assets/images/icons/elevator.svg",
    "Swimming Poor": "assets/images/icons/pool.svg",
    "Bath tub": "assets/images/icons/hot_tub.svg",
    "Patio": "assets/images/icons/patio.svg",
    "Fire pit": "assets/images/icons/fire_pit.svg",
    "BBQ grill": "assets/images/icons/grill.svg",
    "Pool table": "assets/images/icons/pool_table.svg",
    "Indoor fireplace": "assets/images/icons/fireplace.svg",
    "Outdoor dining area": "assets/images/icons/outdoor_dining_area.svg",
    "Exercise equipment": "assets/images/icons/gym_equipment.svg",
    "Wifi": "assets/images/icons/wifi.svg",
    "Kitchen": "assets/images/icons/kitchen.svg",
    "Hair dryer": "assets/images/icons/dryer.svg",
    "Heating": "assets/images/icons/heater.svg",
    "Beach access": "assets/images/icons/beach_access.svg",
    "Lake access": "assets/images/icons/lake_access.svg",
    "EV charger": "assets/images/icons/ev_charger.svg",
    "Free parking": "assets/images/icons/free_parking.svg",
    "Game console": "assets/images/icons/game_console.svg",
    "First aid kit": "assets/images/icons/first_aid_kit.svg",
  };
  static Map<String, String> iconHotelLib = {
    "Breakfast included": "assets/images/icons/coffee.svg",
    "Entertainment": "assets/images/icons/entertainment.svg",
    "Family": "assets/images/icons/family.svg",
    "Heating and cooling": "assets/images/icons/heating_and_coolingg.svg",
    "Home safety": "assets/images/icons/hot_tub.svg",
    "Internet and office": "assets/images/icons/internet_and_office.svg",
    "Location features": "assets/images/icons/fire_pit.svg",
    "Outdoor": "assets/images/icons/pool_table.svg",
    "Parking and facilities": "assets/images/icons/free_parking.svg",
    "Fire extinguisher": "assets/images/icons/fire-extinguisher.svg",
  };
}
